---
# tasks file for base_os
# Change the Hostname 
- name: Disable the hostname via DHCP 
  ansible.builtin.lineinfile:
    path:   /etc/sysconfig/network/dhcp
    regexp: '^DHCLIENT_SET_HOSTNAME='
    line:   DHCLIENT_SET_HOSTNAME="no"
  when:     ansible_os_family|upper == 'SUSE'
- name: Change the hostname 
  hostname:
    name: "{{ hostname }}" 

#Change the time Zone 
- name: Setting OS timezone
  timezone:
    name: "{{ timezone }}"

# Disable the Firewall 
- name: Disbled firewall 
  service: 
    name: firewalld 
    state: stopped 
    enabled: no 

#Configure the Disks 

- include_tasks: disks.yml
